### PR TITLE
Fix app to serve files in S3

### PR DESCRIPTION
**Pull request by bha**
* Fix build script
* Fix bower structure
* Add script to deploy code to S3

*** Need to run bower install - since the bower path has updated ***

### CODE REVIEW

**Comment by shakeelmohamed** [comment]
@bha this still isn't working for me. I wiped my local repo then ran `npm install`, `bower install`, and `grunt build`. Then when I open either `dist/index.html` or `app/index.html` I get the same errors.

I just deployed the app again, and you can see that it doesn't work (this is definitely updated because the logout menu item is there): http://exbedia-admin-app-frontend.s3-website-us-west-2.amazonaws.com/

**Comment by bha** [comment]
grunt-cli v0.1.13
grunt v0.4.5
bower 1.4.1
npm 2.9.1
node v0.12.3

**Comment by bha** [comment]
@shakeelmohamed - After it build, can you try grunt serve?

**Comment by shakeelmohamed** [comment]
@bha yeah `grunt serve` still works, but that doesn't solve the problem

**Comment by bha** [comment]
@shakeelmohamed do you want to merge and try it out? if the CI build pass, and deploy the code to S3 and it works there. Would that consider the problem is fixed?

If not, we can revert this pull request from master. I can't make travis-ci to build and publish pull request files to S3.

**Comment by shakeelmohamed** [comment]
@bha no good

**Comment by bha** [comment]
Just merge it to master and let it build there....

**Comment by bha** [comment]
we can revert it if this doesn't work from the master branch

**Comment by shakeelmohamed** [comment]
still didn't work, as expected

**Comment by bha** [comment]
?I just synced master, clean and build then upload files from list?


it works though.



It looks like there could be something to do with travis-ci?


________________________________

**Comment by shakeelmohamed** [comment]
I think it's the specific versions of node/npm/bower/grunt that have to be just right. I'll try playing around with those later. One or more of those versions is broken for me & what we have configured for Travis CI

**Comment by shakeelmohamed** [comment]
@bha I don't understand how this works for you.

```shell
git clone git@github.com:seattleu/exbedia-admin-app-frontend.git
nvm install 0.12.3
npm install -g npm@2.9.1
npm install -g bower@1.4.1 grunt-cli@0.1.13
cd exbedia-admin-app-frontend
npm install && bower install
grunt build
open dist/index.html
open app/index.html
```

**Comment by bha** [comment]
Just clicked on the link, and it works fine for me though. Not sure what’s missing?

I use the deploy_test.sh script to copy the files to s3 after running grunt build. Actually I changed the s3 bucket what pushing to prod…

I run grunt serve locally during development.

**Comment by shakeelmohamed** [comment]
@bha I know. Open dist/index.html and it shouldn't work, because it doesn't work for me. This is the same problem I've been trying to solve, but you're addressing a different problem: `grunt serve` isn't the problem. Travis CI deployments should work, but they don't because when you open `dist/index.html` there are errors. The Travis CI deployment is literally just copying over the files in `dist` to S3 - so if I can't get `dist/index.html` to work locally it won't work on S3. 

Does that make sense?

**Comment by bha** [comment]
it's a bit odd on how the built out code won't work like a normal html page.

But if you take all the files from the dist folder and prop it to any web service serving the files over http protocol (not file:// protocol) and test it out. Does it work? Try that on nginx or apache or s3.

**Comment by shakeelmohamed** [comment]
@bha no good, I tried it with MAMP (Mac LAMP server)

**Comment by bha** [comment]
For local development, try if you have issue w/ running 'grunt serve'
To deploy a build to server, try if it work by running following commands:

grunt build
./deploy_test.sh  // to use s3cmd to upload files to s3

**Comment by shakeelmohamed** [comment]
@bha I don't have an issue running `grunt serve` I never have. What is `s3cmd`? A library, a bash alias, something else?

**Comment by bha** [comment]
s3cmd is a tool to copy files to s3

brew install s3cmd
s3cmd configure

then run the script

**Comment by shakeelmohamed** [comment]
@bha got it. Let's discuss this on Friday in person

**Pull request merged**
