### PR TITLE
Untested: Added sending welcome email functionality

### PR DESCRIPTION
**Pull request by shakeelmohamed**
Try to send a welcome email on signup by doing an HTTP post to the backend email server, if it fails try again once.  Also, **removed the aws-sdk bower dependency** grunt was breaking it - now we're just referencing it directly by URL.

**TODO: when logging in, if the welcome email hasn't been sent, try to send it again.**

**Also, added about page content**

### CODE REVIEW

**Comment by shakeelmohamed** [comment]
blocked on @biancaflaidar for testing

**Comment by biancaflaidar** [comment]
It worked great when I created an account with a non-SU email address. I received the welcome email right away.
Then I tried creating an account with my SU email address. Didn't get it yet... Funny, it works if we simply send test emails from the console (using the domain) to SU addresses (just checked again with mine).

**Comment by shakeelmohamed** [comment]
@biancaflaidar I think SU is auto-blocking any emails containing exbedia.us, do you want to shoot an email to the IT office and see if they can do anything about it? I'll merge this in at some point then :)

**Comment by biancaflaidar** [comment]
But then why does it work using the console?

**Comment by shakeelmohamed** [comment]
@biancaflaidar Ask Amazon :santa:

**Comment by biancaflaidar** [comment]
You mean send an email to amazon support or SU IT office?

**Comment by shakeelmohamed** [comment]
Why not both? (but yeah I meant SU IT)

**Pull request merged**
