### PR TITLE
Quick fix

### PR DESCRIPTION
**Pull request by biancaflaidar**

### CODE REVIEW

**Comment by shakeelmohamed** [comment]
Not sure if you addressed this in the mobile app, but what if `backendError` is null/undefined? This could possibly happen if the view loads before we do the POST request. 

Otherwise, this is fine

**Comment by shakeelmohamed** [comment]
The logic here needs to be `backendError && backendError != 200` I'm making this change to the mobile app, please do so here.

**Comment by biancaflaidar** [comment]
Made the change

**Comment by shakeelmohamed** [comment]
Thanks

**Pull request merged**
