### PR TITLE
exbediaOwnerID

### PR DESCRIPTION
**Pull request by biancaflaidar**
Used for data access / backend

- needed an ownerID reference in the hotel data to make the connection

### CODE REVIEW

**Comment by shakeelmohamed** [comment]
I'm not against this, but isn't the owner ID the same as the property ID, but prefixed with "private_"?

Can you just do "propertyID.replace("private_", "");?

**Comment by biancaflaidar** [comment]
I like that, let me try it

**Comment by biancaflaidar** [comment]
Oh actually, I'm also using this to differentiate between an Expedia hotel and an Exbedia hotel in Firebase. If a hotel has this exbediaOwnerID property set on signup then you know it's an Exbedia hotel and will getting info on the manager in order to send an email to the manager. So I'd like to keep it...

**Comment by shakeelmohamed** [comment]
@biancaflaidar You can differentiate based on the property ID, you can do what @dkimnguyen is doing in the mobile app. Basically this is your truth test `var isExBEDia = hotelID.indexOf("private_") === 0;`

I see no reason to keep this change if we don't need it

**Pull request closed without merging**
